# Generated by Django 4.0.1 on 2023-03-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='账号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default=0, max_length=32, null=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
