# Generated by Django 4.0.1 on 2023-03-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_friends_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=256, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypt',
            field=models.CharField(default='0', max_length=32, verbose_name='加密算法'),
        ),
    ]
