# Generated by Django 4.0.1 on 2023-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_message_subject_alter_message_encrypt'),
    ]

    operations = [
        migrations.CreateModel(
            name='view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(blank=True, default=0, null=True, verbose_name='访问次数')),
                ('usernum', models.IntegerField(blank=True, default=0, null=True, verbose_name='用户总数')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='name1',
            field=models.CharField(default='', max_length=16, verbose_name='发送者姓名'),
        ),
        migrations.AddField(
            model_name='message',
            name='name2',
            field=models.CharField(default='', max_length=16, verbose_name='接收者姓名'),
        ),
    ]
