# Generated by Django 4.0.1 on 2023-03-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_view_message_name1_message_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=32, verbose_name='发送者')),
                ('user2', models.CharField(max_length=32, verbose_name='接收者')),
                ('name1', models.CharField(default='', max_length=16, verbose_name='发送者姓名')),
                ('name2', models.CharField(default='', max_length=16, verbose_name='接收者姓名')),
                ('p', models.CharField(default='', max_length=256, verbose_name='p')),
                ('g', models.CharField(default='', max_length=256, verbose_name='g')),
                ('encrypt', models.CharField(default='0', max_length=32, verbose_name='加密算法')),
                ('a', models.CharField(default='', max_length=256, verbose_name='a')),
                ('b', models.CharField(default='', max_length=256, verbose_name='b')),
                ('user1ID', models.IntegerField(blank=True, default=0, null=True, verbose_name='发送者ID')),
                ('user2ID', models.IntegerField(blank=True, default=0, null=True, verbose_name='接收者ID')),
            ],
        ),
    ]
