# Generated by Django 4.0.1 on 2023-04-12 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='cyber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='发送者')),
                ('userID', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('cyber', models.CharField(max_length=256, verbose_name='密钥')),
                ('cybername', models.CharField(max_length=256, verbose_name='密钥名称')),
                ('length', models.IntegerField(blank=True, default=0, null=True, verbose_name='密钥长度')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='创建时间'),
        ),
    ]
