# Generated by Django 4.0.1 on 2023-04-12 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_cyber_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyber',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 1), verbose_name='截止日期'),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 1), verbose_name='创建日期'),
        ),
    ]
